apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: btcstuff-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - www.btcstuff.io
        - qr.btcstuff.io
      secretName: btcstuff-tls
  rules:
    - host: "www.btcstuff.io"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: qr-ui
                port:
                  number: 80
    - host: "qr.btcstuff.io"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: qr-ui
                port:
                  number: 80